# ESPirate Zephyr Configuration
# Target: ESP32-S3 (DevKitM / DevKitC)

# Kernel Settings
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=262144

# FPU & Standard C Library for Lua
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_PICOLIBC=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Console & Shell (UART0 over USB CP2102 Bridge)
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_PROMPT_UART="ESPirate> "
CONFIG_SHELL_STACK_SIZE=8192
CONFIG_SHELL_CMD_BUFF_SIZE=512
CONFIG_SHELL_PRINTF_BUFF_SIZE=512
CONFIG_SHELL_WILDCARD=n

# Hardware control & Utilities
CONFIG_GPIO=y
CONFIG_REBOOT=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
