/*
 * Copyright (c) 2026 Alan Mimms / ESPirate
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ESPIRATE_WEB_DASHBOARD_H_
#define ESPIRATE_WEB_DASHBOARD_H_

static const char ESPIRATE_DASHBOARD_HTML[] = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>ESPirate Hardware Sequencer</title>\n"
"<style>\n"
":root { --bg:#0f172a; --card:#1e293b; --text:#f8fafc; --accent:#38bdf8; --pass:#22c55e; --fail:#ef4444; --border:#334155; }\n"
"* { box-sizing: border-box; margin:0; padding:0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }\n"
"body { background: var(--bg); color: var(--text); padding: 1.5rem; max-width: 1200px; margin: auto; }\n"
"header { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid var(--border); padding-bottom: 1rem; margin-bottom: 1.5rem; flex-wrap: wrap; gap: 0.75rem; }\n"
"h1 { font-size: 1.6rem; color: var(--accent); display: flex; align-items: center; gap: 0.5rem; }\n"
".badge { background: #0369a1; color: #e0f2fe; padding: 0.25rem 0.6rem; border-radius: 9999px; font-size: 0.75rem; font-weight: bold; }\n"
".badge.success { background: #15803d; color: #dcfce7; }\n"
".badge.warn { background: #b45309; color: #fef3c7; }\n"
".grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(350px, 1fr)); gap: 1.5rem; margin-bottom: 1.5rem; align-items: start; }\n"
".card { background: var(--card); border: 1px solid var(--border); border-radius: 0.75rem; padding: 1.25rem; transition: padding 0.15s ease; }\n"
".card h2 { font-size: 1.1rem; margin-bottom: 1rem; color: var(--accent); border-bottom: 1px solid var(--border); padding-bottom: 0.4rem; display:flex; justify-content:space-between; align-items:center; cursor: pointer; user-select: none; }\n"
".card h2:hover { color: #7dd3fc; }\n"
".turnstile { display: inline-block; font-size: 0.8rem; margin-right: 0.45rem; color: var(--accent); }\n"
".card.collapsed { padding-top: 0.85rem; padding-bottom: 0.85rem; }\n"
".card.collapsed h2 { margin-bottom: 0; border-bottom: none; padding-bottom: 0; }\n"
".card.collapsed .card-body { display: none; }\n"
".metrics { display: grid; grid-template-columns: repeat(3, 1fr); gap: 0.75rem; text-align: center; margin-bottom: 1rem; }\n"
".metric { background: #0f172a; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid var(--border); }\n"
".metric .val { font-size: 1.7rem; font-weight: bold; }\n"
".metric .lbl { font-size: 0.75rem; color: #94a3b8; text-transform: uppercase; margin-top: 0.25rem; }\n"
".status-bar { display: flex; justify-content: space-between; align-items: center; padding: 0.5rem 0.75rem; background: #0f172a; border-radius: 0.5rem; margin-bottom: 1rem; font-size: 0.9rem; }\n"
"button { background: #0284c7; color: white; border: none; border-radius: 0.4rem; padding: 0.5rem 1rem; font-weight: 600; cursor: pointer; transition: 0.15s; }\n"
"button:hover { background: #0369a1; }\n"
"button.danger { background: #b91c1c; }\n"
"button.danger:hover { background: #991b1b; }\n"
"button.success { background: #15803d; }\n"
"button.success:hover { background: #166534; }\n"
"select, input, textarea { width: 100%; background: #0f172a; border: 1px solid var(--border); color: white; padding: 0.5rem; border-radius: 0.4rem; margin-bottom: 0.75rem; font-family: monospace; font-size: 0.9rem; }\n"
"textarea { height: 160px; resize: vertical; }\n"
".console { background: #020617; border: 1px solid var(--border); border-radius: 0.5rem; padding: 0.75rem; height: 160px; overflow-y: auto; font-family: monospace; font-size: 0.85rem; color: #a7f3d0; white-space: pre-wrap; }\n"
".btn-row { display: flex; gap: 0.5rem; margin-bottom: 0.75rem; }\n"
".toggle-row { display: flex; justify-content: space-between; align-items: center; background: #0f172a; border: 1px solid var(--border); border-radius: 0.5rem; padding: 0.6rem 0.75rem; margin-top: 0.5rem; font-size: 0.85rem; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <div>\n"
"    <h1>🏴‍☠️ ESPirate Hardware Sequencer</h1>\n"
"    <div style=\"color:#94a3b8; font-size:0.85rem; margin-top:0.25rem;\">ESP32-S3 | Exclusive AP / STA Mode | 8MB Octal PSRAM | LittleFS</div>\n"
"  </div>\n"
"  <div style=\"display:flex; gap:0.5rem; align-items:center; flex-wrap:wrap;\">\n"
"    <span class=\"badge\" id=\"mode-badge\">Mode: AP</span>\n"
"    <span class=\"badge\" id=\"ap-info\">AP: ESPirate</span>\n"
"    <a id=\"mdns-badge\" class=\"badge success\" href=\"#\" target=\"_blank\" style=\"text-decoration:none;\">mDNS: espirate.local</a>\n"
"  </div>\n"
"</header>\n"
"\n"
"<div class=\"grid\">\n"
"  <!-- Telemetry Card -->\n"
"  <div class=\"card\" id=\"card-telemetry\">\n"
"    <h2 onclick=\"toggleCard('card-telemetry')\">\n"
"      <span><span class=\"turnstile\">▼</span> Hardware Test Telemetry</span>\n"
"    </h2>\n"
"    <div class=\"card-body\">\n"
"      <div class=\"metrics\">\n"
"        <div class=\"metric\"><div class=\"val\" id=\"telem-total\">0</div><div class=\"lbl\">Total Cycles</div></div>\n"
"        <div class=\"metric\"><div class=\"val\" id=\"telem-pass\" style=\"color:var(--pass);\">0</div><div class=\"lbl\">Passed</div></div>\n"
"        <div class=\"metric\"><div class=\"val\" id=\"telem-fail\" style=\"color:var(--fail);\">0</div><div class=\"lbl\">Failed</div></div>\n"
"      </div>\n"
"      <div class=\"status-bar\">\n"
"        <span>Execution Status:</span>\n"
"        <strong id=\"telem-status\" style=\"color:var(--accent);\">IDLE</strong>\n"
"      </div>\n"
"      <div class=\"btn-row\">\n"
"        <button onclick=\"resetTelemetry()\">Clear Telemetry</button>\n"
"        <button class=\"danger\" onclick=\"resetLuaVM()\">Reset Lua VM</button>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <!-- Wi-Fi Network & Mode Settings Card -->\n"
"  <div class=\"card\" id=\"card-wifi\">\n"
"    <h2 onclick=\"toggleCard('card-wifi')\">\n"
"      <span><span class=\"turnstile\">▼</span> Wi-Fi Network Configuration</span>\n"
"      <span class=\"badge\" id=\"sta-status-badge\" onclick=\"event.stopPropagation()\">AP Mode</span>\n"
"    </h2>\n"
"    <div class=\"card-body\">\n"
"      <div class=\"status-bar\">\n"
"        <span>Mode: <strong id=\"active-mode-display\" style=\"color:var(--accent);\">AP</strong></span>\n"
"        <span>IP: <strong id=\"active-ip-display\" style=\"color:var(--accent); font-family:monospace;\">192.168.4.1</strong></span>\n"
"        <span>mDNS: <a id=\"mdns-link\" href=\"#\" target=\"_blank\" style=\"color:var(--accent); text-decoration:underline;\">espirate.local</a></span>\n"
"      </div>\n"
"      <div class=\"btn-row\" style=\"margin-bottom: 0.75rem;\">\n"
"        <button id=\"btn-mode-ap\" onclick=\"switchWifiMode('ap')\" style=\"flex:1;\">Switch to AP</button>\n"
"        <button id=\"btn-mode-sta\" onclick=\"switchWifiMode('sta')\" style=\"flex:1; background:#334155;\">Switch to STA</button>\n"
"      </div>\n"
"      <div style=\"font-size:0.8rem; color:#94a3b8; margin-bottom:0.25rem;\">Soft-AP Network SSID:</div>\n"
"      <div class=\"btn-row\">\n"
"        <input type=\"text\" id=\"wifi-ap-ssid\" placeholder=\"Soft-AP SSID (e.g. ESPirate-CEA0)\" style=\"margin-bottom:0;\">\n"
"        <button onclick=\"saveApSsid()\">Save AP</button>\n"
"      </div>\n"
"      <div style=\"font-size:0.8rem; color:#94a3b8; margin-top:0.4rem; margin-bottom:0.25rem;\">Station (STA) Credentials:</div>\n"
"      <input type=\"text\" id=\"wifi-sta-ssid\" placeholder=\"Wi-Fi Network SSID to join\">\n"
"      <input type=\"password\" id=\"wifi-sta-pass\" placeholder=\"Wi-Fi Password (stored safely)\">\n"
"      <div class=\"btn-row\">\n"
"        <button class=\"success\" onclick=\"saveAndConnectWifi()\">📡 Connect & Switch to STA</button>\n"
"        <button class=\"danger\" onclick=\"forgetWifi()\">Forget STA</button>\n"
"      </div>\n"
"      <div class=\"toggle-row\">\n"
"        <span>Pretend Internet Connectivity (Android 17 / 204 Probe)</span>\n"
"        <input type=\"checkbox\" id=\"fake-internet-toggle\" onchange=\"toggleFakeInternet(this.checked)\" style=\"width:auto; margin:0; cursor:pointer;\">\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"grid\">\n"
"  <!-- Test Sequencer Card -->\n"
"  <div class=\"card\" id=\"card-sequencer\">\n"
"    <h2 onclick=\"toggleCard('card-sequencer')\">\n"
"      <span><span class=\"turnstile\">▼</span> Sequencer Execution</span>\n"
"    </h2>\n"
"    <div class=\"card-body\">\n"
"      <label style=\"font-size:0.8rem; color:#94a3b8;\">Select Script from /lfs:</label>\n"
"      <select id=\"script-select\" onchange=\"loadSelectedScript()\"></select>\n"
"      <div class=\"btn-row\">\n"
"        <button class=\"success\" onclick=\"runScript(true)\">▶ Run (Background)</button>\n"
"        <button onclick=\"runScript(false)\">Run (Sync)</button>\n"
"      </div>\n"
"      <div class=\"console\" id=\"run-console\">System ready. Select a script to execute.</div>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <!-- Script Editor Card -->\n"
"  <div class=\"card\" id=\"card-storage\">\n"
"    <h2 onclick=\"toggleCard('card-storage')\">\n"
"      <span><span class=\"turnstile\">▼</span> LittleFS Storage & Scripts</span>\n"
"      <span class=\"badge\" id=\"storage-badge\" onclick=\"event.stopPropagation()\">LittleFS</span>\n"
"    </h2>\n"
"    <div class=\"card-body\">\n"
"      <div style=\"font-size:0.8rem; color:#94a3b8; margin-bottom:0.5rem;\" id=\"storage-summary\">Storage: Loading...</div>\n"
"      <div class=\"btn-row\" style=\"margin-bottom:0.5rem; flex-wrap:wrap;\">\n"
"        <input type=\"text\" id=\"script-filename\" placeholder=\"/lfs/myscript.lua\" style=\"margin-bottom:0; flex:2; min-width:140px;\">\n"
"        <button onclick=\"newScript()\" title=\"Create new script\">➕ New</button>\n"
"        <button onclick=\"saveScript()\" title=\"Save to LittleFS\">💾 Save</button>\n"
"        <button onclick=\"renameScript()\" title=\"Rename current script\">✏️ Rename</button>\n"
"        <button class=\"danger\" onclick=\"deleteScript()\" title=\"Delete script\">🗑️ Del</button>\n"
"        <button onclick=\"refreshScripts()\" title=\"Refresh file list\">🔄</button>\n"
"      </div>\n"
"      <textarea id=\"script-content\" placeholder=\"-- Enter Lua test script here...\"></textarea>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"grid\">\n"
"  <!-- Interactive Lua REPL Card -->\n"
"  <div class=\"card\" id=\"card-repl\" style=\"grid-column: 1 / -1;\">\n"
"    <h2 onclick=\"toggleCard('card-repl')\">\n"
"      <span><span class=\"turnstile\">▼</span> Interactive Lua Command (REPL)</span>\n"
"    </h2>\n"
"    <div class=\"card-body\">\n"
"      <div class=\"btn-row\">\n"
"        <input type=\"text\" id=\"lua-eval-input\" placeholder=\"e.g. gpio.high(4) or print(sys.uptime())\" style=\"margin-bottom:0;\" onkeydown=\"if(event.key==='Enter')evalLua()\">\n"
"        <button onclick=\"evalLua()\">⚡ Eval</button>\n"
"      </div>\n"
"      <div class=\"console\" id=\"eval-console\">Interactive Lua console ready.</div>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<script>\n"
"function log(cId, msg) {\n"
"  const c = document.getElementById(cId);\n"
"  c.textContent += (c.textContent ? '\\n' : '') + msg;\n"
"  c.scrollTop = c.scrollHeight;\n"
"}\n"
"\n"
"function toggleCard(cardId) {\n"
"  const c = document.getElementById(cardId);\n"
"  if (!c) return;\n"
"  const isCollapsed = c.classList.toggle('collapsed');\n"
"  const t = c.querySelector('.turnstile');\n"
"  if (t) t.textContent = isCollapsed ? '▶' : '▼';\n"
"}\n"
"\n"
"async function fetchTelemetry() {\n"
"  try {\n"
"    const res = await fetch('/api/telemetry');\n"
"    if (res.ok) {\n"
"      const data = await res.json();\n"
"      document.getElementById('telem-total').innerText = data.total || 0;\n"
"      document.getElementById('telem-pass').innerText = data.pass || 0;\n"
"      document.getElementById('telem-fail').innerText = data.fail || 0;\n"
"      document.getElementById('telem-status').innerText = data.status || 'IDLE';\n"
"    }\n"
"  } catch (e) {}\n"
"}\n"
"\n"
"async function switchWifiMode(mode) {\n"
"  log('run-console', '[Wi-Fi] Switching mode to ' + mode.toUpperCase() + '...');\n"
"  const res = await fetch('/api/wifi/mode', {\n"
"    method: 'POST',\n"
"    headers: { 'Content-Type': 'application/json' },\n"
"    body: JSON.stringify({ mode: mode })\n"
"  });\n"
"  if (res.ok) {\n"
"    log('run-console', '[Wi-Fi] Mode switch request submitted: ' + mode.toUpperCase());\n"
"    setTimeout(fetchWifi, 1500);\n"
"  } else {\n"
"    const txt = await res.text();\n"
"    log('run-console', '[Wi-Fi] Switch error: ' + txt);\n"
"    alert('Mode switch failed: ' + txt);\n"
"  }\n"
"}\n"
"\n"
"async function saveApSsid() {\n"
"  const ssid = document.getElementById('wifi-ap-ssid').value.trim();\n"
"  if (!ssid) return alert('Enter Soft-AP SSID');\n"
"  log('run-console', '[Wi-Fi] Setting Soft-AP SSID to ' + ssid + '...');\n"
"  const res = await fetch('/api/wifi', {\n"
"    method: 'POST',\n"
"    headers: { 'Content-Type': 'application/json' },\n"
"    body: JSON.stringify({ ap_ssid: ssid })\n"
"  });\n"
"  if (res.ok) {\n"
"    log('run-console', '[Wi-Fi] Soft-AP SSID updated.');\n"
"    setTimeout(fetchWifi, 1000);\n"
"  }\n"
"}\n"
"\n"
"async function fetchWifi() {\n"
"  try {\n"
"    const res = await fetch('/api/wifi');\n"
"    if (res.ok) {\n"
"      const data = await res.json();\n"
"      const mode = data.mode || 'AP';\n"
"      document.getElementById('mode-badge').innerText = 'Mode: ' + mode;\n"
"      document.getElementById('active-mode-display').innerText = mode;\n"
"      const btnAp = document.getElementById('btn-mode-ap');\n"
"      const btnSta = document.getElementById('btn-mode-sta');\n"
"      if (mode === 'AP') {\n"
"        btnAp.style.background = '#0284c7';\n"
"        btnSta.style.background = '#334155';\n"
"        document.getElementById('active-ip-display').innerText = (data.ap ? data.ap.ip : '192.168.4.1');\n"
"      } else {\n"
"        btnAp.style.background = '#334155';\n"
"        btnSta.style.background = '#0284c7';\n"
"        document.getElementById('active-ip-display').innerText = (data.sta && data.sta.connected) ? data.sta.ip : '0.0.0.0';\n"
"      }\n"
"      if (data.ap) {\n"
"        document.getElementById('ap-info').innerText = 'AP: ' + data.ap.ssid + ' (' + data.ap.clients + ' clients)';\n"
"        if (!document.getElementById('wifi-ap-ssid').value) {\n"
"          document.getElementById('wifi-ap-ssid').value = data.ap.ssid;\n"
"        }\n"
"      }\n"
"      if (data.mdns) {\n"
"        const url = 'http://' + data.mdns;\n"
"        const ml = document.getElementById('mdns-link');\n"
"        ml.innerText = data.mdns;\n"
"        ml.href = url;\n"
"        const mb = document.getElementById('mdns-badge');\n"
"        mb.innerText = 'mDNS: ' + data.mdns;\n"
"        mb.href = url;\n"
"      }\n"
"      if (data.sta) {\n"
"        const badge = document.getElementById('sta-status-badge');\n"
"        if (mode === 'STA') {\n"
"          if (data.sta.connected) {\n"
"            badge.innerText = 'Connected: ' + data.sta.ssid;\n"
"            badge.className = 'badge success';\n"
"          } else {\n"
"            badge.innerText = 'Connecting to ' + (data.sta.ssid || 'AP') + '...';\n"
"            badge.className = 'badge warn';\n"
"          }\n"
"        } else {\n"
"          badge.innerText = 'AP Mode (' + (data.ap ? data.ap.clients : 0) + ' clients)';\n"
"          badge.className = 'badge success';\n"
"        }\n"
"        if (data.sta.ssid && !document.getElementById('wifi-sta-ssid').value) {\n"
"          document.getElementById('wifi-sta-ssid').value = data.sta.ssid;\n"
"        }\n"
"      }\n"
"      if (typeof data.fake_internet === 'boolean') {\n"
"        document.getElementById('fake-internet-toggle').checked = data.fake_internet;\n"
"      }\n"
"    }\n"
"  } catch (e) {}\n"
"}\n"
"\n"
"async function saveAndConnectWifi() {\n"
"  const ssid = document.getElementById('wifi-sta-ssid').value.trim();\n"
"  const pass = document.getElementById('wifi-sta-pass').value;\n"
"  if (!ssid) return alert('Please enter Wi-Fi SSID');\n"
"  log('run-console', '[Wi-Fi] Connecting to ' + ssid + '...');\n"
"  const res = await fetch('/api/wifi', {\n"
"    method: 'POST',\n"
"    headers: { 'Content-Type': 'application/json' },\n"
"    body: JSON.stringify({ ssid: ssid, password: pass })\n"
"  });\n"
"  document.getElementById('wifi-sta-pass').value = '';\n"
"  if (res.ok) {\n"
"    log('run-console', '[Wi-Fi] Credentials saved and connection initiated.');\n"
"    setTimeout(fetchWifi, 1500);\n"
"  } else {\n"
"    log('run-console', '[Wi-Fi] Error initiating connection.');\n"
"  }\n"
"}\n"
"\n"
"async function forgetWifi() {\n"
"  if (!confirm('Forget saved Wi-Fi credentials?')) return;\n"
"  const res = await fetch('/api/wifi/forget', { method: 'POST' });\n"
"  if (res.ok) {\n"
"    document.getElementById('wifi-sta-ssid').value = '';\n"
"    document.getElementById('wifi-sta-pass').value = '';\n"
"    log('run-console', '[Wi-Fi] Credentials forgotten and disconnected.');\n"
"    fetchWifi();\n"
"  }\n"
"}\n"
"\n"
"async function toggleFakeInternet(enable) {\n"
"  const res = await fetch('/api/wifi/config', {\n"
"    method: 'POST',\n"
"    headers: { 'Content-Type': 'application/json' },\n"
"    body: JSON.stringify({ fake_internet: enable })\n"
"  });\n"
"  if (res.ok) {\n"
"    log('run-console', '[Pretend Internet] ' + (enable ? 'Enabled (204 Probe active)' : 'Disabled'));\n"
"  }\n"
"}\n"
"\n"
"async function resetTelemetry() {\n"
"  await fetch('/api/telemetry/reset', { method: 'POST' });\n"
"  fetchTelemetry();\n"
"}\n"
"\n"
"async function resetLuaVM() {\n"
"  await fetch('/api/reset', { method: 'POST' });\n"
"  log('run-console', '[System] Lua VM reset requested.');\n"
"}\n"
"\n"
"async function refreshStorage() {\n"
"  try {\n"
"    const res = await fetch('/api/storage');\n"
"    if (res.ok) {\n"
"      const data = await res.json();\n"
"      if (data.mounted) {\n"
"        const totalKb = Math.round(data.total_bytes / 1024);\n"
"        const usedKb = Math.round(data.used_bytes / 1024);\n"
"        const freeKb = Math.round(data.free_bytes / 1024);\n"
"        const chipMb = data.chip_size_mb || 0;\n"
"        document.getElementById('storage-badge').innerText = (chipMb ? (chipMb + ' MB Flash') : (totalKb >= 1024 ? (Math.round(totalKb/1024) + ' MB') : (totalKb + ' KB')));\n"
"        document.getElementById('storage-summary').innerText = 'Usage: ' + usedKb + ' KB used / ' + freeKb + ' KB free (Total: ' + totalKb + ' KB)';\n"
"      }\n"
"    }\n"
"  } catch (e) {}\n"
"}\n"
"\n"
"async function refreshScripts() {\n"
"  try {\n"
"    refreshStorage();\n"
"    const res = await fetch('/api/scripts');\n"
"    if (res.ok) {\n"
"      const files = await res.json();\n"
"      const sel = document.getElementById('script-select');\n"
"      const curVal = sel.value;\n"
"      sel.innerHTML = '';\n"
"      files.forEach(f => {\n"
"        const opt = document.createElement('option');\n"
"        opt.value = f.name;\n"
"        opt.text = f.name + ' (' + f.size + ' B)';\n"
"        sel.appendChild(opt);\n"
"      });\n"
"      if (files.length > 0) {\n"
"        if (curVal && files.some(f => f.name === curVal)) {\n"
"          sel.value = curVal;\n"
"        } else {\n"
"          loadSelectedScript();\n"
"        }\n"
"      }\n"
"    }\n"
"  } catch (e) {}\n"
"}\n"
"\n"
"function newScript() {\n"
"  document.getElementById('script-filename').value = '/lfs/new_script.lua';\n"
"  document.getElementById('script-content').value = '-- New ESPirate Lua Script\\nprint(\"Hello from new script!\")\\n';\n"
"  document.getElementById('script-content').focus();\n"
"}\n"
"\n"
"async function renameScript() {\n"
"  const cur = document.getElementById('script-filename').value.trim();\n"
"  if (!cur) return alert('No file selected');\n"
"  const baseName = cur.startsWith('/lfs/') ? cur.substring(5) : cur;\n"
"  const newName = prompt('Enter new filename for ' + baseName + ':', baseName);\n"
"  if (!newName || newName === baseName) return;\n"
"  const res = await fetch('/api/script/rename', {\n"
"    method: 'POST',\n"
"    headers: { 'Content-Type': 'application/json' },\n"
"    body: JSON.stringify({ old_name: baseName, new_name: newName })\n"
"  });\n"
"  if (res.ok) {\n"
"    log('run-console', '[Storage] Renamed ' + baseName + ' to ' + newName);\n"
"    await refreshScripts();\n"
"    document.getElementById('script-filename').value = '/lfs/' + newName;\n"
"  } else {\n"
"    alert('Failed to rename script');\n"
"  }\n"
"}\n"
"\n"
"async function deleteScript() {\n"
"  const cur = document.getElementById('script-filename').value.trim();\n"
"  if (!cur) return alert('No file selected');\n"
"  const baseName = cur.startsWith('/lfs/') ? cur.substring(5) : cur;\n"
"  if (!confirm('Are you sure you want to delete ' + baseName + '?')) return;\n"
"  const res = await fetch('/api/script/delete', {\n"
"    method: 'POST',\n"
"    headers: { 'Content-Type': 'application/json' },\n"
"    body: JSON.stringify({ name: baseName })\n"
"  });\n"
"  if (res.ok) {\n"
"    log('run-console', '[Storage] Deleted ' + baseName);\n"
"    document.getElementById('script-filename').value = '';\n"
"    document.getElementById('script-content').value = '';\n"
"    refreshScripts();\n"
"  } else {\n"
"    alert('Failed to delete script');\n"
"  }\n"
"}\n"
"\n"
"async function loadSelectedScript() {\n"
"  const sel = document.getElementById('script-select');\n"
"  if (!sel.value) return;\n"
"  const res = await fetch('/api/script?name=' + encodeURIComponent(sel.value));\n"
"  if (res.ok) {\n"
"    const text = await res.text();\n"
"    document.getElementById('script-filename').value = '/lfs/' + sel.value;\n"
"    document.getElementById('script-content').value = text;\n"
"  }\n"
"}\n"
"\n"
"async function saveScript() {\n"
"  const fn = document.getElementById('script-filename').value;\n"
"  const content = document.getElementById('script-content').value;\n"
"  if (!fn) return alert('Enter filename');\n"
"  const res = await fetch('/api/script', {\n"
"    method: 'POST',\n"
"    headers: { 'Content-Type': 'application/json' },\n"
"    body: JSON.stringify({ name: fn, content: content })\n"
"  });\n"
"  if (res.ok) {\n"
"    log('run-console', '[Storage] Saved ' + fn);\n"
"    refreshScripts();\n"
"  } else {\n"
"    log('run-console', '[Storage] Error saving ' + fn);\n"
"  }\n"
"}\n"
"\n"
"async function runScript(bg) {\n"
"  const sel = document.getElementById('script-select');\n"
"  if (!sel.value) return;\n"
"  const path = '/lfs/' + sel.value;\n"
"  log('run-console', '[Trigger] Executing ' + path + (bg ? ' in background...' : ' synchronously...'));\n"
"  const res = await fetch('/api/run', {\n"
"    method: 'POST',\n"
"    headers: { 'Content-Type': 'application/json' },\n"
"    body: JSON.stringify({ file: path, bg: bg })\n"
"  });\n"
"  const txt = await res.text();\n"
"  log('run-console', txt);\n"
"}\n"
"\n"
"async function evalLua() {\n"
"  const inp = document.getElementById('lua-eval-input');\n"
"  const code = inp.value.trim();\n"
"  if (!code) return;\n"
"  log('eval-console', '> ' + code);\n"
"  inp.value = '';\n"
"  const res = await fetch('/api/run', {\n"
"    method: 'POST',\n"
"    headers: { 'Content-Type': 'application/json' },\n"
"    body: JSON.stringify({ code: code, bg: false })\n"
"  });\n"
"  const txt = await res.text();\n"
"  log('eval-console', txt);\n"
"}\n"
"\n"
"setInterval(fetchTelemetry, 1000);\n"
"setInterval(fetchWifi, 3000);\n"
"refreshScripts();\n"
"fetchTelemetry();\n"
"fetchWifi();\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif /* ESPIRATE_WEB_DASHBOARD_H_ */
